stages:
  - release

# Release on tag creation
release:
  image: python:3.7-slim-buster
  tags:
    - docker
  stage: release
  before_script:
    - apt-get update -qq && apt-get install -y -qq git wget zip rsync composer unzip php7.3-xml xmlstarlet > /dev/null
    - pip3 install gitlab-release > /dev/null
  script:
    - echo ${PACKAGE_NAME}
    - cd src && zip -r ../shopgate_rromnienablement-${CI_COMMIT_TAG}.zip . && cd ..
    - gitlab-release shopgate_rromnienablement-${CI_COMMIT_TAG}.zip
  only:
    - tags
