<?php

use Retailred\Storefront\Helper\Data;
use Retailred\Storefront\Model\Config;

/** @var Retailred\Storefront\Block\Product $this */

/** @var Retailred\Storefront\Helper\Data $helper */
$helper = $this->helper(Retailred\Storefront\Helper\Data::class);

if ($helper->getConfig(Config::XML_PATH_API_STATUS) === 'disabled') {
    return;
}

?>

<style type="text/css">
    .rr-wrapper {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-items: center;
        transform: translateY(-30px);
    }
    #rr-dropin {
        flex-grow: 1;
    }
    #rr-omni-reserve-button{
        width: 100%;
        line-height: 2.2rem;
    }

    #rr-omni #rr-omni-custom, #rr-omni-reserve-button {
        <?= $helper->getConfig(Config::XML_PATH_DESIGN_COLORS) ?>
    }
</style>

<div class="rr-wrapper">
    <div id="rr-dropin"></div>
</div>

<script type="text/javascript">
  require([
    'jquery',
    'domReady!'
  ], function ($) {
    $('.box-tocart').append($('.rr-wrapper'));
  });
</script>

